### ISSUE TITLE
Add monthly forecast export by client

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/Harvest-Forecast-tools#3]
Some clients like to know which days each developer is available on his projects, to help planning meeting and have a better visibility on the team velocity to come.

What could be done:

- for each client:
  - each last day of a month, fetch the forecast of the next month
  - build a nice calendar (excel? image? ical?)
  - send it by email to the harvest contact for this client, or on a Slack channel we use with them
- on demand:
  - allow to ask for a new export of the current/next month anytime, via button or slack command

WDYT?

**Comment by ternel** [comment]
👍  for the "on demand" part.

**Comment by xavierlacot** [comment]
The project https://github.com/jolicode/forecast-tools allows to expose a webview the forecast for any client / project.
